<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeId = $storeManager->getStore()->getStoreId();
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>


    <div class="ib-landing-page">
        <img src="https://www.ibottles.co.uk/media/logo/websites/1/ibottles_logo_2020.png" alt="iBottles" />
        <h1>Thank you for visiting <span>iBottles</span>.</h1>
        <p>The website will reopen on 30th December.</p>
        <p>We hope you're having a safe and happy <strong>Christmas</strong>.</p>
        <p>Best Wishes</p>
        <p>The iBottles Team</p>
    </div>
    <!--<div class="ib-landing-top">
        <ul>
            <li>
                <img src="<?=$mediaUrl?>landing/images/ib-landing-img1.png" alt="iBottles -- Merry Christmas" />
            </li>
            <li>
                <img src="<?=$mediaUrl?>landing/images/ib-landing-img2.png" alt="iBottles -- Merry Christmas" />
            </li>
            <li>
                <img src="<?=$mediaUrl?>landing/images/ib-landing-img3.png" alt="iBottles -- Merry Christmas" />
            </li>
            <li>
                <img src="<?=$mediaUrl?>landing/images/ib-landing-img4.png" alt="iBottles -- Merry Christmas" />
            </li>
        </ul>
    </div>
    <div class="ib-landing-bottom">
        <div class="inner-content">
            <h2 class="page-caption">
                Wishing you a <span><span class="red">Safe &amp;</span> Merry <span class="yellow">Xmas</span></span>
            </h2>
            <p><img src="<?=$mediaUrl?>landing/images/opening-hrs.jpg" alt="iBottles -- Merry Christmas" /></p>
            <p>FIG will be closing for Christmas at 5.30pm on Wednesday, December 23rd, and reopening at 9am on Monday, January 4th, 2021.</p>
        </div>
    </div>-->
