<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $mediaUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    //$baseUrl='http://ibottles.webpreview.co/';
   
?>

<ul>
<li><a href="https://www.trustpilot.com/review/www.ibottles.co.uk?utm_medium=trustbox&utm_source=Horizontal" target="_blank" rel="noopener"><img src="<?php echo $mediaUrl ?>customerService.png" alt="customerService">
<h4>Outstanding Customer Service</h4>
<p>We're proud of our reputation</p></a>
</li>
<li><a href="<?php echo $this->getUrl('shipping'); ?>"> <img src="<?php echo $mediaUrl ?>delivery.png" alt="delivery">
<h4>Free Shipping</h4>
<p>On all orders over £50 to UK mainland</p></a>
</li>
</ul>
