<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_MegaMenu
 */
?>
<?php
/** @var \Amasty\MegaMenu\Block\Html\Topmenu $block */
?>
<section class="ammenu-menu-wrapper -desktop"
         data-ammenu-js="desktop-menu"
         data-mage-init='{"amastyMegaMenu":{"stickyStatus": <?= $block->escapeHtml($block->getStickyState()); ?>,
              "desktopStatus": 1 }}'>
    <nav class="ammenu-main-container" data-action="navigation">
        <ul class="ammenu-items">
            <?php
            foreach ($block->getMainNodes() as $mainNode):
                if (!$block->isNeedDisplay($mainNode->getId(), $mainNode->getStatus(), $block::DESKTOP_VIEW)) {
                    continue;
                }

                $url = $mainNode->getUrl() ?: '#';
                $widthMode = $block->escapeHtml($block->getWidth($mainNode));
                $widthValue = $block->getWidthValue($mainNode);
                $mainNodeContent = $block->getContent($mainNode);
                ?>
                <li class="ammenu-item category-item -main -<?= $block->escapeHtml($widthMode); ?>
                <?= $block->escapeHtml($block->getHighLightClass($mainNode)); ?>
                <?= $block->escapeHtml($mainNode->getPositionClass()); ?>"
                >
                    <a href="<?= $block->escapeUrl($url) ?>"
                       class="ammenu-link -main<?= ($mainNodeContent) ?' -parent': '' ?>"
                       title="<?= $block->escapeHtml($mainNode->getName()); ?>">
                        <?= $block->escapeHtml($mainNode->getName()); ?>
                        <?php if ($label = $mainNode->getLabel()): ?>
                            <span class="ammenu-label"
                                  style="color: <?= $block->escapeHtml($mainNode->getLabelTextColor() ?: '#000') ?> !important;
                                          background-color: <?= $block->escapeHtml($mainNode->getLabelBackgroundColor() ?: '#fff') ?> !important;">
                            <?= $block->escapeHtml($label); ?>
                        </span>
                        <?php endif; ?></a>
                    <?php if (/* @noEscape */ $mainNodeContent): ?>
                        <div class="ammenu-submenu-container ammenu-submenu -<?= $block->escapeHtml($widthMode); ?>"
                             data-ammenu-js="menu-submenu"
                                <?= ($widthValue) ? 'style="width: ' . $block->escapeHtml($widthValue) . 'px"': '' ?>>
                            <?= /* @noEscape */ $mainNodeContent; ?>
                        </div>
                    <?php endif;?>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php echo  $this->getLayout()->getBlock('top.search')->toHtml(); ?>
        
    </nav>
</section>
