<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<!DOCTYPE html>
<style>
		body {
			font-family: 'Barlow Condensed', sans-serif;
			font-size: 22px;
			color: #404041;
		}
	</style>
	<link href="https://fonts.googleapis.com/css?family=Barlow+Condensed:400,400i,500,600,700" rel="stylesheet">
	<div style="text-align:center;">
		<br /><br />
		<div style="text-align: center;">
			<img src="https://www.ibottles.co.uk/pub/media/logo/stores/1/ibottles-logo.png">
		</div>
		<br /><br />

		<!-- <p>We are currently undergoing maintenance, to place an order please call on +44 (0) 1298 815000</p> -->
		<p>We are currently undergoing maintenance</p>

		<p>Our apologies for any inconvenience.<br>The iBottles Team</p>

	</div>