<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$mediaUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$banners = $objectManager->create('Custom\Banner\Model\Banner')->getCollection();
$banners->addFieldToFilter('status',1);
?>

<ul class="homepage-banner owl-carousel owl-theme">
    <?php foreach($banners as $banner){ ?>
    
    <li>
        <img src="<?php echo $mediaUrl.'banner/'.$banner['image']; ?>" />
        <div class="banner-content">
            <h2><?php echo $banner['title']; ?></h2>
            <p><?php echo $banner['comment']; ?></p>
            <?php if(!empty($banner['link'])){?>
                <a class="btn-cust-link" href="<?php echo $banner['link']?>">Learn More</a>
            <?php }?>
        </div>
    </li>
    <?php }?>
</ul>


<script type="text/javascript">
    require(['jquery', 'bannersliderLib'],function($){
      $(function() {
	   $('.homepage-banner').owlCarousel({
	     items:1,
	     nav:true,
	     autoplay: false,
	     loop:true,
             dots:false,
	     autoHeight: true,
	 })
    })
      
    });

</script>



