<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_order = $block->getOrder() ?>
<?php $_invoice = $block->getInvoice() ?>
<?php if ($_invoice) : ?>
    <?php $_invoices = [$_invoice]; ?>
<?php else : ?>
    <?php $_invoices = $_order->getInvoiceCollection() ?>
<?php endif; ?>
<?php foreach ($_invoices as $_invoice) : ?>

<?php
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $timezoneInterface =  $objectManager->get('Magento\Framework\Stdlib\DateTime\TimezoneInterface');
     $dateTime = $objectManager->create(\Magento\Framework\Stdlib\DateTime\DateTimeFactory::class)
            ->create();
   // $createdAt = $timezoneInterface->date($createdAt)->format('d F Y');
    $invoiceCreatedAt=$_order->getCreatedAt();
     $invoiceCreatedAt = $timezoneInterface->formatDateTime(
            $invoiceCreatedAt,
            \IntlDateFormatter::SHORT,
            \IntlDateFormatter::NONE,
            null,
            null,
            'yyyy-MM-dd'
        );
        $invoiceCreatedAtDate = $dateTime->date('d F Y', $invoiceCreatedAt);
    
    
?>

<div class="order-details-items invoice">
    <div class="block1">
    <div class="order-title">
        <p>Invoice # <?=  $_invoice->getIncrementId() ?></p>
        <p>Order # <?php echo $_order->getIncrementId()?></p>
        <p>Order Date: <?php echo  $invoiceCreatedAtDate;  ?></p>
    </div>
    <div class="address-block">
            <table>
                <tr>
                    <td>Sold To : </td>
                      <td>Ship To : </td>                  
                </tr>
                <tr>
                    <td>
                        <div class="box-content">
                    <?php $_billing = $_invoice->getbillingAddress() ?>
                    <address><?= /* @noEscape */ $block->formatAddress($_order->getBillingAddress(), 'html') ?></address>
                   </div>
                    </td>
                    <td>
                         <div class="box-content">
                    <?php $_shipping = $_invoice->getShippingAddress() ?>
                    <address><?= /* @noEscape */ $block->formatAddress($_shipping, 'html') ?></address>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    
    <div class="block2">
        <table>
                <tr>
                    <td>Payment Method:</td>
                      <td>Shipping Method:</td>                  
                </tr>
                <tr>
                    <td>
                       <div class="box-content">
                            <?= $block->getPaymentInfoHtml() ?>
                    </div>
                    </td>
                    <td>
                       <div class="box-content">
                    <?php if ($_order->getShippingDescription()) : ?>
                        <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                        <br />(Total Shipping Charges £ <?php //echo number_format($_order->getShippingInclTax(),2) ?><?php echo number_format($_order->getShippingAmount(),2) ?>)
                    <?php else : ?>
                        <?= $block->escapeHtml(__('No shipping information available')) ?>
                    <?php endif; ?>
                </div>
                    </td>
                </tr>
            </table>
    </div>
    
    <div class="table-wrapper table-order-items invoice">
        <table class="data table table-order-items invoice" id="my-invoice-table-<?= (int) $_invoice->getId() ?>">
            <caption class="table-caption"><?= $block->escapeHtml(__('Items Invoiced')) ?></caption>
            <thead>
            <tr>
                <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                <th class="col price"><?= $block->escapeHtml(__('Price')) ?></th>
                <th class="col qty"><?= $block->escapeHtml(__('Qty ')) ?></th>
                
                <th class="col subtotal"><?= $block->escapeHtml(__('Subtotal')) ?></th>
            </tr>
            </thead>
            <?php $_items = $_invoice->getItemsCollection(); ?>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
            <tfoot>
                <?= $block->getInvoiceTotalsHtml($_invoice) ?>
            </tfoot>
        </table>
    </div>
   
</div>
<?php endforeach; ?>
