<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/** @var \Magento\Catalog\Pricing\Render\PriceBox $block */

/** @var \Magento\Catalog\Pricing\Price\TierPrice $tierPriceModel */
$tierPriceModel = $block->getPrice();
$tierPrices = $tierPriceModel->getTierPriceList();
$msrpShowOnGesture = $block->getPriceType('msrp_price')->isShowPriceOnGesture();
$product = $block->getSaleableItem();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
    $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
    $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
  $currencySymbol = $currency->getCurrencySymbol(); 




?>



<?php if (count($tierPrices)) : ?>

 <?php $i=0; foreach ($tierPrices as $index => $price) : ?>
    <?php $items[$i]=$price['price_qty']-1;  $i++ ; $j=$i;  ; ?>
 <?php endforeach; ?>

<div class="price-tier_price simple-product">
    <div class="tier-title">Individual unit prices:</div>
    <ul class="<?= $block->escapeHtmlAttr(($block->hasListClass() ? $block->getListClass() : 'prices-tier items ')) ?>">
        <?php $i=0; foreach ($tierPrices as $index => $price) : $i++ ?>
            <li class="item" <?php if($i%2==0) {?> style="background: #fff" <?php } ?> >
            <?php if($i<$j) { ?>
            <?php echo $price['price_qty'] .'-' . $items[$i] ; ?>  <span class="price-container price-tier_price"><span class="price"><?php echo $currencySymbol .  $price['price'] .' ea.' ?> </span></span>   
            <?php } else { ?>
              <?php echo $price['price_qty'] .'+' ; ?>  <span class="price-container price-tier_price"><span class="price"><?php echo $currencySymbol . $price['price'] .' ea.' ?> </span></span>   
            
            <?php } ?>
            
            </li>
        <?php endforeach; ?>
        <li class="foot">For larger quantities, please email <a href="mailto:sales@ibottles.co.uk">sales@ibottles.co.uk</a> or call <a href="tel:01298 815 000">01298 815 000</a>.</li>
    </ul>
</div>
 
    
    <?php if ($msrpShowOnGesture) :?>
        <script type="text/x-magento-init">
            {
                ".product-info-main": {
                    "addToCart": {
                        "origin": "tier",
                        "addToCartButton": "#product_addtocart_form [type=submit]",
                        "inputQty": "#qty",
                        "attr": "[data-tier-price]",
                        "productForm": "#product_addtocart_form",
                        "productId": "<?= (int) $productId ?>",
                        "productIdInput": "input[type=hidden][name=product]",
                        "isSaleable": "<?= (bool) $isSaleable ?>"
                    }
                }
            }
        </script>
    <?php endif;?>
<?php endif; ?>

