<?php $objectManager      = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeId = $storeManager->getStore()->getStoreId();
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$_imagehelper = $objectManager->get('Magento\Catalog\Helper\Image');

?>


<div class="invprint">
    <div class="logo">
        <img src="<?php echo  $mediaUrl ?>iBottle_Logo_Colour_AUG2020.png" style="height:70px" />
    </div>
    <div class="address">
        <p>iBottles, Bridgeholme Industrial Estate
<br/>Chinley, High Peak, Derbyshire SK23 6DX
<br/>Tel: +44 (0) 1298 815000
<br/>Email: sales@ibottles.co.uk
<br/>VAT Registration No: GB 673 4718 12
   </p>     
    </div>
    
</div>