<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
    $pid= $product->getId();
    $finalPrice=$product->getFinalPrice();
    
    
     $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
    $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
     $currencySymbol = $currency->getCurrencySymbol();
       $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $url=$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
     $mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
  ?>
  
  
  <link rel="stylesheet" href="<?php echo $mediaUrl ?>banner/js/simple-lightbox.css?v2.2.1" />
 <style>
       

       .gallery a img {
          
            -webkit-transition: -webkit-transform .15s ease;
            -moz-transition: -moz-transform .15s ease;
            -o-transition: -o-transform .15s ease;
            -ms-transition: -ms-transform .15s ease;
            transition: transform .15s ease;
            position: relative;
            height: 75px!important;
        }
  .gallery .msg {
      font-size: 12px;
      color: #ef3e36;
      margin-bottom: 5px;
  }
      
    </style>
  
  
  
<div>
    <input type="hidden" id="reset-price" value="0">
    <input type="hidden" id="selcap-price" value="0">
<h2 id="sel-cap">*Select your cap</h2>
  <div id="updateBox">Cap options will appear once you have selected your other options above</div>
  
   <div id="selectedBox" style="display: none;" >
    
    <div id="img-box" class="gallery"></div>
      <div id="nmr"></div>
      <!-- <div id="prr"></div>
       <div class="vat">+VAT</div>-->
       <div class="change"><a href="javascript:void(0)" id="change"> Change</a></div>
        
   </div>  

</div>

  <script  type="text/javascript"  src="<?php echo $mediaUrl ?>banner/js/simple-lightbox.js?v2.2.1"></script> 

<script type="text/javascript">
require(["jquery"], function(jQuery) {
    
    jQuery('#qty').attr('disabled','disabled');
    jQuery('#qty').val(1);
    jQuery('.qtyplus').hide();
    jQuery('.qtyminus').hide();
          
         jQuery('#product-addtocart-button').hide();
          jQuery('#fake').show();

            jQuery( "#fake" ).click(function() {
 
            jQuery( "#attributecap-error").show();
             setTimeout(function (){
              
                  jQuery( "#attributecap-error").hide();
               }, 3000);  
            
          });
  
  jQuery(".product-options-wrapper select[id^='attribute']").first().on('change', function() {
    
       
      jQuery('#qty').attr('disabled','disabled');
       jQuery('#qty').val(1);
      jQuery('.qtyplus').hide();
      jQuery('.qtyminus').hide();
    
       
  
       });
  
  
  
 jQuery(".product-options-wrapper select[id^='attribute']").last().on('change', function() {
      setTimeout(function (){
        
         jQuery('#qty').removeAttr('disabled');
         jQuery('#qty').val(1);
         jQuery('.qtyplus').show();
         jQuery('.qtyminus').show();
        
        
        simpleId=jQuery("input[name=selected_configurable_option]").val();
       // alert(simpleId);
    jQuery("#updateBox").html('');
       jQuery("#selectedBox").css("display", "none");
       jQuery("#updateBox").css("display", "block");
       document.getElementById("related-products-field").value = '';
       
       
        jQuery.ajax({
        url: "<?php echo $url ?>banner/index",
        type: "post",
        data: {simpleId: simpleId},
        success: function (response) {

            jQuery("#updateBox").html(response);
        },
        error: function(jqXHR, textStatus, errorThrown) {
           console.log(textStatus, errorThrown);
        }
  
         
                 });
        
      }, 500);    
      
      
     });
 
 ///// Tier price calculation 
 
jQuery('#qty').bind('input', function() {
    
    
    tirePriceCalculation();
     
});
 
 
 function tirePriceCalculation()
    {
        simpleId1=jQuery("input[name=selected_configurable_option]").val();
       if(simpleId1){
       express_qty=jQuery('#qty').val();
       cap_price=jQuery('#selcap-price').val();
      
        jQuery.ajax({
        url: "<?php echo $url ?>banner/index/express",
        type: "post",
        data: {simpleId1: simpleId1,express_qty:express_qty,cap_price:cap_price},
        success: function (response) {

          res= response;
            jQuery("#price2").html(res);
            
              var str='<span class="price"><?php echo $currencySymbol ?>'+ document.getElementById("price2").innerHTML+'</span>'
              document.getElementById("product-price-<?php echo $pid ?>").innerHTML=str;
              document.getElementById("reset-price").value=parseFloat(res).toFixed(2);
            
        },
        error: function(jqXHR, textStatus, errorThrown) {
           console.log(textStatus, errorThrown);
        }
  
         
                 });
        
        
       }
        
    }
 
 
 
  jQuery(".product-options-wrapper select[id^='attribute']").on('change', function(){
     setTimeout(function (){
       var str=document.getElementById("product-price-<?php echo $pid ?>").innerHTML;
          var res=str.replace('<?php echo $currencySymbol ?>','');
            
           res=res.replace('<span class="price">','');
              res=res.replace('</span>','');
           document.getElementById("price2").innerHTML=res;
            }, 500);    
     });
 
 
 
 
 
   
      jQuery("#change").click(function() { 

       jQuery('#product-addtocart-button').hide();
      jQuery('#fake').show();
        jQuery("#selectedBox").css("display", "none");
       jQuery("#updateBox").css("display", "block");
       document.getElementById("related-products-field").value = '';
        document.getElementById("selcap-price").value = '0';
           tirePriceCalculation();
        //document.getElementById("price2").innerHTML=<?php echo $finalPrice ?>;
        
        document.getElementById("price2").innerHTML=document.getElementById("reset-price").value;
        var str='<span class="price"><?php echo $currencySymbol ?>'+ document.getElementById("price2").innerHTML+'</span>'
        document.getElementById("product-price-<?php echo $pid ?>").innerHTML=str;
         document.getElementById("sel-cap").innerHTML= '*Select your cap';
       
   
      });
   
   
   
   

    
    });
    
    
   
     function getCap(id)
        {
            //alert(id);
             jQuery('#product-addtocart-button').show();
             jQuery('#fake').hide();
            document.getElementById("updateBox").style.display = "none";
            document.getElementById("selectedBox").style.display = "block";
           
            
                var price_string="  Cost: "+document.getElementById("price-"+id).innerHTML;
           
              document.getElementById("nmr").innerHTML= document.getElementById("nm-"+id).innerHTML + price_string ;
            
                document.getElementById("sel-cap").innerHTML= 'Selected Cap :';
              
            var bigimg=document.getElementById("imgbig"+id).value;
              
              document.getElementById("img-box").innerHTML='<a href="'+bigimg +'" class="big">' + document.getElementById("img-"+id).innerHTML+'</a><p class="msg">Click on image to enlarge</p>';
            
            var cap_price=document.getElementById("price-"+id).innerHTML.substring(1);
             document.getElementById("selcap-price").value=parseFloat(cap_price).toFixed(2);
            
            document.getElementById("reset-price").value=parseFloat(document.getElementById("price2").innerHTML);
            
             var price_2=parseFloat(document.getElementById("price2").innerHTML)+parseFloat(cap_price);
             
            
             
             document.getElementById("price2").innerHTML=parseFloat(price_2).toFixed(2);
             
             var str='<span class="price"><?php echo $currencySymbol ?>'+ document.getElementById("price2").innerHTML+'</span>'
             
             document.getElementById("product-price-<?php echo $pid ?>").innerHTML=str;
             
             document.getElementById("related-products-field").value = id;
             
               (function() {
        var $gallery = new SimpleLightbox('.gallery a', {});
    })();
           
        }
    
    
    
    </script>





