 <?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $mediaUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $storeCode = $storeManager->getStore()->getCode();
    $baseUrl='https://www.ibottles.co.uk/';
?>

<div class="footer-container">

    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-top-content')->toHtml(); ?>

    <div class="footer">
        <?php //echo $this->getChildHtml() ?>
        <div class="footer-inner">
            <div class="links first">
                <div class="block-title">
                    <div class="address">
                        <img src="<?php echo $mediaUrl ?>footer-logo.png" alt="footer-logo">
                      <span class="foot-address"><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('address')->toHtml(); ?>
                    </div>
                      </span>
                </div>
            </div>
            
            <div class="links mid1">
                <div class="block-title">
               
                    
                    <p><?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('additional-links')->toHtml(); ?></p>
               
                   
                </div>
            </div>
            <div class="links mid2">
                <div class="block-title">
                    <div class="block-title">
                    <strong><span>Change Language:</span></strong>
                    </div>
              
                     <div class="language">
                       <p>
                           <a href="<?php echo $baseUrl ?>"><img <?php if ($storeCode == "default") { ?>style="opacity: 0.3;"<?php } ?> src="<?php echo $mediaUrl ?>uk.svg" alt="uk" /> </a>
                           
                           <a href="https://www.ibottles.fr/"><img <?php if ($storeCode == "fr_4") { ?>style="opacity: 0.3;"<?php } ?> src="<?php echo $mediaUrl ?>fr.svg" alt="fr" /> </a>
                           
                           <a href="https://www.ibottles.de/"><img <?php if ($storeCode == "de_3") { ?>style="opacity: 0.3;"<?php } ?>  src="<?php echo $mediaUrl ?>de.svg" alt="de"> </a>
                           
                           <a href="https://www.ibottles.es/"><img <?php if ($storeCode == "es_6_4") { ?>style="opacity: 0.3;"<?php } ?>  src="<?php echo $mediaUrl ?>es.svg" alt="es"> </a>
                           
                           <a href="https://www.ibottles.it/"><img <?php if ($storeCode == "it_5") { ?>style="opacity: 0.3;"<?php } ?>   src="<?php  echo $mediaUrl ?>it.svg"  alt="it"> </a>
                       </p>
               </div>
                              
                    
                    </p>
                </div>
            </div>
            
            <div class="links last">
                    <div class="block-title">
                        <strong><span>Social Media</span></strong>
                    </div>
                    <span class="facebook">
                        <a href="https://www.facebook.com/ibottles2015" target="_blank"> facebook</a>
                    </span>
                    <span class="twitter">
                        <a href="https://twitter.com/ibottles2015" target="_blank">twitter</a>
                    </span>
                    <span class="Youtube">
                        <a href="https://www.youtube.com/channel/UCy_27XojeAig3zo_iGR5_YQ" target="_blank"> Youtube</a>
                    </span>
            </div>
        </div>
    </div>
            



