<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>

<?php
$allTiers = $_product->getTierPrice();
$checktiers = array_filter($allTiers);
?>

<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
    $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
    $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
     $currencySymbol = $currency->getCurrencySymbol();
       $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $url=$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
     
     
     ?>

<div id="prr1">
  <span class="symbol"><?php echo $currencySymbol ?></span>  <span class="price2" id="price2"><?php echo number_format($_product->getFinalPrice(),2); ?></span>
</div>
<div class="vat">+vat</div>

<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
              <?php /*Add Plus Button */ ?>
             <input type='button' value='+' class='qtyplus' field='qty' />
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                       />
                        <?php /*Add Minus Button */ ?>
            <input type='button' value='-' class='qtyminus' field='qty' />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            
              <button type="button"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="fake" disabled="disabled" style="display: none">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <div for="attributecap" generated="true" class="mage-error" style="display: none" id="attributecap-error">Cap is a required .</div>
            
            
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>



<?php /*JS FOR +-*/ ?>
<script type="text/javascript">
        //&lt;![CDATA[
        require(['jquery'], function ($) {
            setTimeout(function () {
                // This button will increment the value
                jQuery('.qtyplus').click(function (e) {
                    // Stop acting like a button
                    e.preventDefault();
                    // Get the field name
                    fieldName = jQuery(this).attr('field');
                    // Get its current value
                    var currentVal = parseInt(jQuery('input[name=' + fieldName + ']').val());
                    // If is not undefined
                    if (!isNaN(currentVal)) {
                        // Increment
                        jQuery('input[name=' + fieldName + ']').val(currentVal + 1);
                    } else {
                        // Otherwise put a 0 there
                        jQuery('input[name=' + fieldName + ']').val(0);
                    }
                     tirePriceCalculation();
                });
                // This button will decrement the value till 0
                jQuery(".qtyminus").click(function (e) {
                    // Stop acting like a button
                    e.preventDefault();
                    // Get the field name
                    fieldName = jQuery(this).attr('field');
                    // Get its current value
                    var currentVal = parseInt(jQuery('input[name=' + fieldName + ']').val());
                    // If it isn't undefined or its greater than 0
                    if (!isNaN(currentVal) && currentVal > 0) {
                        // Decrement one
                        jQuery('input[name=' + fieldName + ']').val(currentVal - 1);
                    } else {
                        // Otherwise put a 0 there
                        jQuery('input[name=' + fieldName + ']').val(0);
                    }
                    
                     tirePriceCalculation();
                });
            }, 100);
        });
        //]]&gt;
    </script>

<?php  $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
    $pid= $_product->getId();
  ?> 
<script type="text/javascript">
    
     function tirePriceCalculation()
    {
        simpleId1=jQuery("input[name=selected_configurable_option]").val();
       if(simpleId1){
       express_qty=jQuery('#qty').val();
       cap_price=jQuery('#selcap-price').val();
      
        jQuery.ajax({
        url: "<?php echo $url ?>banner/index/express",
        type: "post",
        data: {simpleId1: simpleId1,express_qty:express_qty,cap_price:cap_price},
        success: function (response) {

          res= response;
            jQuery("#price2").html(res);
            
              var str='<span class="price"><?php echo $currencySymbol ?>'+ document.getElementById("price2").innerHTML+'</span>'
              document.getElementById("product-price-<?php echo $pid ?>").innerHTML=str;
              document.getElementById("reset-price").value=res;
            
        },
        error: function(jqXHR, textStatus, errorThrown) {
           console.log(textStatus, errorThrown);
        }
  
         
                 });
        
        
       }
        
    }
    
    
</script>

 
<style>
.product-info-main .product-info-price .price-box .old-price .price {
font-size: 25px !important;
color: #999;
text-decoration: line-through;
font-weight: 600;
line-height: normal;
}

.product-info-main .product-info-price .price-box .old-price .vat {
    font-size: 16px;
    line-height: 24px;
    color: #999;
    text-decoration: line-through;
}
.product-info-main .product-info-price .price-box .normal-price {
    margin-right: 10px;
}
</style>
 


